behaviors:
  USVAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 3.0e-4 
      beta: 1.0e-2
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 1000000
    time_horizon: 256
    summary_freq: 10000
    checkpoint_interval: 50000
    threaded: true

environment_parameters:
  num_static_obstacles:
    curriculum:
      - name: Lesson1_NoObstacles
        completion_criteria:
          measure: reward
          behavior: USVAgent
          signal_smoothing: true
          min_lesson_length: 20
          threshold: 700
        value: 0
      - name: Lesson2_Static3
        completion_criteria:
          measure: reward
          behavior: USVAgent
          signal_smoothing: true
          min_lesson_length: 20
          threshold: 800
        value: 3
      - name: Lesson3_Static5
        completion_criteria:
          measure: reward
          behavior: USVAgent
          signal_smoothing: true
          min_lesson_length: 20
          threshold: 800
        value: 5
      - name: Lesson4_Static6
        completion_criteria:
          measure: reward
          behavior: USVAgent
          signal_smoothing: true
          min_lesson_length: 20
          threshold: 800
        value: 6
      - name: Lesson5_Static7
        completion_criteria:
          measure: reward
          behavior: USVAgent
          signal_smoothing: true
          min_lesson_length: 20
          threshold: 1000
        value: 7
      - name: Lesson6_AllStatic
        completion_criteria:
          measure: reward
          behavior: USVAgent
          signal_smoothing: true
          min_lesson_length: 10000
          threshold: 99999
        value: 8
  
  num_moving_obstacles:
    curriculum:
      - name: Lesson1_NoObstacles
        completion_criteria:
          measure: reward
          behavior: USVAgent
          signal_smoothing: true
          min_lesson_length: 20
          threshold: 700
        value: 0
      - name: Lesson2_NoMoving
        completion_criteria:
          measure: reward
          behavior: USVAgent
          signal_smoothing: true
          min_lesson_length: 20
          threshold: 800
        value: 0
      - name: Lesson3_Moving1
        completion_criteria:
          measure: reward
          behavior: USVAgent
          signal_smoothing: true
          min_lesson_length: 20
          threshold: 800
        value: 1
      - name: Lesson4_Moving2
        completion_criteria:
          measure: reward
          behavior: USVAgent
          signal_smoothing: true
          min_lesson_length: 20
          threshold: 800
        value: 2
      - name: Lesson5_Moving3
        completion_criteria:
          measure: reward
          behavior: USVAgent
          signal_smoothing: true
          min_lesson_length: 20
          threshold: 1000
        value: 3
      - name: Lesson6_AllMoving
        completion_criteria:
          measure: reward
          behavior: USVAgent
          signal_smoothing: true
          min_lesson_length: 10000
          threshold: 99999
        value: 4